# Generated by Django 4.1.7 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0003_user_password_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
