# Generated by Django 4.1.7 on 2023-08-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0005_alter_user_age_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='age123',
        ),
    ]
