# Generated by Django 4.1.7 on 2023-08-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0006_rename_age_user_age123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age123',
            new_name='age',
        ),
    ]
