# Generated by Django 3.2.20 on 2023-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0007_rename_age123_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
