# Generated by Django 5.0 on 2024-02-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0010_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
