# Generated by Django 5.0.2 on 2024-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0012_questionstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstable',
            name='Questions',
        ),
        migrations.AddField(
            model_name='questionstable',
            name='Answer',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='questionstable',
            name='Question',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstable',
            name='Option1',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstable',
            name='Option2',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstable',
            name='Option3',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstable',
            name='Option4',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstable',
            name='QId',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
