# Generated by Django 5.0.2 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0013_remove_questionstable_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.EmailField(max_length=254)),
                ('picture', models.URLField()),
                ('updated_at', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField()),
                ('sub', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
