# Generated by Django 5.0.2 on 2024-03-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
